Auth/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("myapp.urls")),
]

myapp/urls.py
from django.urls import path
from . import views

app_name = "myapp"
urlpatterns = [
    path("", views.index, name="index"),
    path("create-user/", views.create_user, name="create_user"),
    path(
        "complete-profile/<uuid:userId>/",
        views.complete_profile,
        name="complete_profile",
    ),
    path("app/", views.app, name="app"),
]

myapp/models.py
import uuid
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    id = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=50, default="")

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["username"]

    def __str__(self):
        return self.username

myapp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpRequest, HttpResponse
from django.contrib.auth import get_user_model
from django.conf import settings
from django.contrib.auth.models import auth
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response

# user object
User = get_user_model()


def index(request: HttpRequest) -> HttpResponse:
    context = {
        "HANKO_API_URL": settings.HANKO_API_URL
    }
    return render(request, "myapp/index.html", context)


@api_view(["POST"])
def create_user(request: HttpRequest) -> Response:
    if request.method == "POST":
        userId = request.data.get("userId")
        email = request.data.get("email")

        if User.objects.filter(email=email).exists():
            return Response(
                {"error": "User with email already exists"},
                status=status.HTTP_400_BAD_REQUEST,
            )

        user = User.objects.create_user(
            id=userId, email=email, username=" ", password=" "
        )
        user.save()

        return Response({"status": "success"}, status=status.HTTP_201_CREATED)


def complete_profile(request: HttpRequest, userId) -> HttpResponse:
    user = get_object_or_404(User, id=userId)

    if user.username not in ["", " "]:
        # authenticate request

        user = auth.authenticate(userId= user.id, email=user.email)

        if user is not None:
            auth.login(request, user)

        return redirect("myapp:app")

    if request.method == "POST":
        username = request.POST.get("username")

        user.username = username
        user.save()

        # authenticate request

        user = auth.authenticate(userId=user.id, email=user.email)

        if user is not None:
            auth.login(request, user)

        return redirect("myapp:app")
    return render(request, "myapp/complete-profile.html")


def app(request: HttpRequest) -> HttpResponse:
    print("USER", request.user)
    context = {
        "HANKO_API_URL": settings.HANKO_API_URL
    }
    return render(request, "myapp/logout.html", context)

myapp/templates/myapp/complete-profile.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Complete Profile</title>
</head>
<body>
  <div class="container">
    <form method="post" id="complete-profile-form">
      {% csrf_token %}
      <h2>Complete profile</h2>
      <input 
        type="text"
        name="username"
        id="username"
        placeholder="Username"
       />
      <!-- Add other profile fields here -->

      <button id="btn-blue">Continue</button>
    </form>
  </div>
</body>
</html>

myapp/templates/myapp/index.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Passkey auth: Django</title>
  </head>
  <body>

    <div class="container">
      <hanko-auth />
    </div>

    <script>
      const CREATE_USER_ENDPOINT = "{% url 'myapp:create_user' %}";
      const COMPLETE_PROFILE_ENDPOINT = "/complete-profile";
      const HANKO_API_URL = "{{ HANKO_API_URL }}";
    </script>
    <script type="module" src="{% static 'js/main.js' %}"></script>
  </body>
</html>

myapp/templates/myapp/logout.html
{% load static %}
<!doctype html>
<html>
  <head>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" >
    <title>Logout</title>
  </head>
  <body>
    <div class="container">
      <button class="logout-btn" id="logout-btn">Logout</button>
      <div>
        <hanko-profile />
      </div>
    </div>

    <script>
      const HANKO_API_URL = "{{ HANKO_API_URL }}";
    </script>
    <script src="{% static 'js/main.js' %}" type="module"></script>
  <body>
</html>